sudo: true
language: node_js
node_js:
  - "4.2.2"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - psql -c "CREATE DATABASE midas;" -U postgres
  - psql -c "CREATE USER midas WITH PASSWORD 'midas';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE midas to midas;" -U postgres
  - psql -c "ALTER SCHEMA public OWNER TO midas;" -U postgres
before_deploy: npm install -g https://github.com/18F/cf-blue-green/tarball/master
env:
  global:
    - CF_APP=openopps
    - CF_API=https://api.cloud.gov
    - CF_USERNAME=deploy-open-opportunities
    - CF_ORGANIZATION=open-opportunities
    - B_DOMAIN=18f.gov
    - secure: "EYl3NnLIJBH0LplugWMpXyPphV05ScdGHCrwCGv/enynALxwpWKv9iXg9sqm8g4NCTqJTdx3kdPlnPrWIz3Zj70QFFk5vRohh1xcuKs1Mf2lqCW5sSPmpDQlTWPoD2cAVIOJd2TXxOHhhs1lSWVCp/Eld5l0U/XdDpzi7U9feQk="
deploy:
  - provider: script
    script: export CF_SPACE=prod && cf-blue-green-travis
    on:
      branch: master
  - provider: script
    script: export CF_SPACE=staging && cf-blue-green-travis
    on:
      branch: staging
  - provider: script
    script: export CF_SPACE=dev && cf-blue-green-travis
    on:
      branch: dev
